[package]
name = "flac"
version = "0.0.1"
authors = ["Jens Nockert <jens@nockert.se>"]

[features]
complete-tests = []

[lib]
name = "flac"
path = "src/flac.rs"

[dependencies.aurora]
git = "https://github.com/audiocogs/aurora.rs"